apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cd-manager
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
      - rbac.authorization.k8s.io
      - roles.rbac.authorization.k8s.io
      - authorization.k8s.io
      - networking.k8s.io
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cd-binding
subjects:
  - kind: ServiceAccount
    name: cd
    namespace: default
roleRef:
  kind: ClusterRole
  name: cd-manager
  apiGroup: rbac.authorization.k8s.io
