apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datatorch.fullname" . }}-api
  labels:
    app: {{ include "datatorch.name" . }}-api
    {{- include "datatorch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "datatorch.name" . }}-api
      {{- include "datatorch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "datatorch.name" . }}-api
        {{- include "datatorch.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: datatorch-api
          image: gcr.io/datatorch/graphql:{{ .Values.api.tag }}
          env:
            - name: LOGGER_LEVEL
              value: {{ .Values.backend.logging }}
            - name: SECRET
              value: {{ .Values.secret | quote }}
            - name: LICENSE_EMAIL
              value: {{ .Values.licenseEmail | quote }}
            - name: LICENSE_KEY
              value: {{ .Values.licenseKey | quote }}
            - name: FRONTEND_FQDN
              value: {{ .Values.webclientFQDN | quote }}
            - name: API_FQDN
              value: {{ .Values.apiFQDN | quote }}
            - name: JWT_HTTP_ONLY
              value: "true"
            - name: JWT_SAME_SITE
              value: "strict"
            - name: DISABLE_LOCAL_STORAGE
              value: "true"
              # Database configuration
            - name: DATABASE_HOST
              value: {{ default (printf "%s-postgresql" .Release.Name) .Values.backend.database.host | quote}}
            - name: DATABASE_NAME
              value: {{ default .Values.postgresql.postgresqlDatabase .Values.backend.database.name | quote }}
            - name: DATABASE_USERNAME
              value: {{ default .Values.postgresql.postgresqlUsername .Values.backend.database.username | quote}}
            - name: DATABASE_PASSWORD
              value: {{ default .Values.postgresql.postgresqlPassword .Values.backend.database.password | quote }}
            - name: DATASET_PORT
              value: {{ default .Values.postgresql.service.port .Values.backend.database.port | quote }}
              # Redis configuration
            - name: REDIS_HOST
              value: {{ default (printf "%s-redis-master" .Release.Name) .Values.backend.redis.host | quote}}
            - name: REDIS_PORT
              value: {{ default .Values.redis.redisPort .Values.backend.redis.port | quote}}
            - name: REDIS_PASSWORD
              value: {{ default .Values.redis.password .Values.backend.redis.password | quote }}
          ports:
            - containerPort: 4000
          # livenessProbe:
          #   httpGet:
          #     path: /graphql
          #     port: 4000
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
      imagePullSecrets:
        - name: regcred